<a href="https://colab.research.google.com/github/esttefiCarde/Tareas_Mineria_datos-/blob/main/Clase4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Dataset.csv")

In [6]:
df.head()

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,1,AI Engineer,Startup,Retail,Canada,Remote,Senior,2,Master,0,0,0,1,0,158322,6,2024,Low,4
1,2,Machine Learning Engineer,MNC,Technology,Australia,Hybrid,Mid,0,Bachelor,1,1,1,0,1,163666,11,2026,High,9
2,3,Machine Learning Engineer,MNC,Technology,Germany,Onsite,Mid,14,Master,1,0,1,0,1,158556,3,2026,High,9
3,4,Business Analyst,Startup,Healthcare,Germany,Remote,Mid,9,Master,0,1,0,1,1,95775,3,2025,High,7
4,5,Data Scientist,MNC,Healthcare,Germany,Hybrid,Mid,5,Master,1,1,1,0,0,111873,12,2021,Low,2

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10345 entries, 0 to 10344
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job_id                10345 non-null  int64
 1   job_title             10345 non-null  object
 2   company_size          10345 non-null  object
 3   company_industry      10345 non-null  object
 4   country               10345 non-null  object
 5   remote_type           10345 non-null  object
 6   experience_level      10345 non-null  object
 7   years_experience      10345 non-null  int64
 8   education_level       10345 non-null  object
 9   skills_python         10345 non-null  int64
 10  skills_sql            10345 non-null  int64
 11  skills_ml             10345 non-null  int64
 12  skills_deep_learning  10345 non-null  int64
 13  skills_cloud          10345 non-null  int64
 14  salary                10345 non-null  int64
 15  job_posting_month     10345 non-null  int64
 16  job_posting_year      10345 non-null  int64
 17  hiring_urgency        10345 non-null  object
 18  job_openings          10345 non-null  int64
dtypes: int64(11), object(8)
memory usage: 1.5+ MB

In [7]:
df.columns

Index(['job_id', 'job_title', 'company_size', 'company_industry', 'country',
       'remote_type', 'experience_level', 'years_experience',
       'education_level', 'skills_python', 'skills_sql', 'skills_ml',
       'skills_deep_learning', 'skills_cloud', 'salary', 'job_posting_month',
       'job_posting_year', 'hiring_urgency', 'job_openings'],
      dtype='object')

In [9]:
cant_categoria = df['company_industry'].value_counts()
print(cant_categoria)

company_industry
Technology    1787
E-commerce    1744
Finance       1724
Healthcare    1715
Education     1704
Retail        1671
Name: count, dtype: int64

In [25]:
df.isnull()

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10340,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10341,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10342,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10343,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10344,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [27]:
df.isnull().sum()

job_id                  0
job_title               0
company_size            0
company_industry        0
country                 0
remote_type             0
experience_level        0
years_experience        0
education_level         0
skills_python           0
skills_sql              0
skills_ml               0
skills_deep_learning    0
skills_cloud            0
salary                  0
job_posting_month       0
job_posting_year        0
hiring_urgency          0
job_openings            0
dtype: int64

In [11]:
df['remote_type'].value_counts()

remote_type
Remote    3513
Hybrid    3420
Onsite    3412
Name: count, dtype: int64

In [14]:
df.describe().round()

,job_id,years_experience,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,job_openings
count,10345.0,10345.0,10345.0,10345.0,10345.0,10345.0,10345.0,10345.0,10345.0,10345.0,10345.0
mean,5173.0,7.0,0.0,1.0,1.0,0.0,1.0,113438.0,7.0,2023.0,5.0
std,2986.0,4.0,0.0,1.0,0.0,1.0,0.0,31389.0,3.0,2.0,3.0
min,1.0,0.0,0.0,0.0,0.0,0.0,0.0,45083.0,1.0,2020.0,1.0
25%,2587.0,3.0,0.0,0.0,0.0,0.0,0.0,89715.0,4.0,2021.0,3.0
50%,5173.0,7.0,0.0,1.0,1.0,0.0,1.0,113082.0,6.0,2023.0,5.0
75%,7759.0,11.0,1.0,1.0,1.0,1.0,1.0,134894.0,10.0,2025.0,7.0
max,10345.0,14.0,1.0,1.0,1.0,1.0,1.0,204143.0,12.0,2026.0,9.0

In [16]:
df.shape

(10345, 19)

In [29]:
df['salary'].describe()
#

count     10345.00000
mean     113438.22726
std       31389.20106
min       45083.00000
25%       89715.00000
50%      113082.00000
75%      134894.00000
max      204143.00000
Name: salary, dtype: float64

In [36]:
df['company_size'].value_counts()

company_size
Startup       2656
MNC           2593
Medium        2548
Enterprise    2548
Name: count, dtype: int64